# Generated by Django 5.1.2 on 2024-10-13 01:57

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField()),
                ("date", models.DateField(auto_now_add=True, verbose_name="投稿日")),
                ("what_done", models.TextField(verbose_name="本日の作業内容")),
                ("what_not_done", models.TextField(blank=True, verbose_name="本日の課題")),
                ("what_learned", models.TextField(blank=True, verbose_name="本日の取得スキル")),
                (
                    "summary_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="study_summaries/",
                        verbose_name="まとめノート",
                    ),
                ),
            ],
            options={
                "verbose_name": "勉強記録",
                "verbose_name_plural": "勉強記録一覧",
            },
        ),
    ]
