# Generated by Django 5.1.2 on 2024-10-13 02:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recordapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="date",
            field=models.DateField(verbose_name="投稿日"),
        ),
    ]
